# 指定Eureka服务地址
#eureka:
#  client:
#    service-url:
#      defaultZone: http://root:root@localhost:8761/eureka,http://root:root@localhost:8762/eureka

#指定服务的名称
#spring:
#  application:
#    name: SEARCH
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#server:
#  port: 8083



spring:
  datasource:
    url: jdbc:mysql://localhost/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
#    url: jdbc:mysql://192.168.220.133:8066/TESTDB01?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: mycat
#    password: 123456
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
       date-format: yyyy-MM-dd HH:mm:ss
       time-zone: GMT+8
mybatis-plus:
  mapper-locations: classpath*:/mappers/**/*.xml


