user:
    desc: java工程师
logging.level.com.alibaba.nacos.client.naming: WARN


spring:
  datasource:
    url: jdbc:mysql://localhost/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
#    url: jdbc:mysql://192.168.220.133:8066/TESTDB01?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: mycat
#    password: 123456
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
       date-format: yyyy-MM-dd HH:mm:ss
       time-zone: GMT+8
mybatis-plus:
  mapper-locations: classpath*:/mappers/**/*.xml